//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public Asignatura()
        {
            this.ProfesorAsignaturas = new HashSet<ProfesorAsignatura>();
            this.Tutorias = new HashSet<Tutoria>();
        }
    
        public int Asignatura_ID { get; set; }
        public string Asignatura_Nombre { get; set; }
        public string Asignatura_Descripcion { get; set; }
        public Nullable<bool> Asignatura_Estado { get; set; }
    
        public virtual ICollection<ProfesorAsignatura> ProfesorAsignaturas { get; set; }
        public virtual ICollection<Tutoria> Tutorias { get; set; }
    }
}
