//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itinerario
    {
        public int Itinerario_ID { get; set; }
        public Nullable<int> Tutoria_ID { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public System.DateTime Fecha_Termino { get; set; }
    
        public virtual Tutoria Tutoria { get; set; }
    }
}
