//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfesorAsignatura
    {
        public int Pro_asig_ID { get; set; }
        public Nullable<int> Profesor_ID { get; set; }
        public Nullable<int> Asignatura_ID { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
