//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.UsuarioRoles = new HashSet<UsuarioRole>();
        }
    
        public int Rol_ID { get; set; }
        public string Rol_Nombre { get; set; }
        public Nullable<bool> Rol_Estado { get; set; }
    
        public virtual ICollection<UsuarioRole> UsuarioRoles { get; set; }
    }
}
