//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.ProfesorAsignatura = new HashSet<ProfesorAsignatura>();
            this.Tutorias = new HashSet<Tutorias>();
            this.Tutorias1 = new HashSet<Tutorias>();
            this.UsuarioRoles = new HashSet<UsuarioRoles>();
        }
    
        public string Usuario_Matricula { get; set; }
        public string Usuario_Nombre { get; set; }
        public string Usuario_Apellido1 { get; set; }
        public string Usuario_Correo { get; set; }
        public string Usuario_Contraseña { get; set; }
        public string Usuario_Telefono { get; set; }
        public string Usuario_Descripcion { get; set; }
        public Nullable<bool> Usuario_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfesorAsignatura> ProfesorAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutorias> Tutorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutorias> Tutorias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioRoles> UsuarioRoles { get; set; }
    }
}
