//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioRole
    {
        public int Us_Rol_ID { get; set; }
        public Nullable<int> Usuario_ID { get; set; }
        public Nullable<int> Rol_ID { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
