//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tutorias_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TutoriasDBEntities : DbContext
    {
        public TutoriasDBEntities()
            : base("name=TutoriasDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asignatura> Asignaturas { get; set; }
        public DbSet<Itinerario> Itinerarios { get; set; }
        public DbSet<ProfesorAsignatura> ProfesorAsignaturas { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Tutoria> Tutorias { get; set; }
        public DbSet<UsuarioRole> UsuarioRoles { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
    }
}
